name: Generate CDN URL

on:
  push:
    paths:
      - '**/*'  # Este patrón incluye todos los archivos en todos los directorios

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log CDN URL
        run: |
          echo "Archivos modificados o añadidos:"
          if git rev-parse HEAD^ > /dev/null 2>&1; then
            # Existe un commit anterior, listar archivos cambiados
            for file in $(git diff --name-only --diff-filter=A HEAD^ HEAD); do
              echo "https://cdn.jsdelivr.net/gh/${{ github.repository }}@${{ github.ref }}/$file"
            done
          else
            # No existe un commit anterior, listar todos los archivos en el repo
            for file in $(git ls-files); do
              echo "https://cdn.jsdelivr.net/gh/${{ github.repository }}@${{ github.ref }}/$file"
            done
          fi
